publishDir = "../docs"

# Site settings
baseURL = "//"
languageCode = "en-US"
title = "tiago.dev"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2020 @ tiago.dev"

[params.custom.css]
  enable = true

[params]

  # Metadata for search engines and social sharing
  author = "Tiago Sommer Damasceno"
  description = "Tiago's personal website"
  shareImage = "images/social.jpg"
  twitterHandle = "tiagosomda"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/background.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Blog"
        url = "https://notes.tiago.dev"

      [[params.links.list1.link]]
        text = "Email"
        url = "mailto:tiago@somda.net"

      [[params.links.list1.link]]
        text = "GitHub"
        url = "https://github.com/tiagosomda"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "LinkedIn"
        url = "https://www.linkedin.com/in/tiagosomda/"

      [[params.links.list2.link]]
        text = "Twitter"
        url = "https://www.twitter.com/tiagosomda"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Projects"

      [[params.links.list3.link]]
        text = "Camp Fireworks"
        url = "https://sidequestvr.com/app/1287/camp-fireworks"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
