publishDir = "../docs"

# Site settings
baseURL = ""
languageCode = "en-US"
title = "tiago.dev"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = "//"

# Copyright
copyright = "tiago.dev"

[params.custom.css]
  enable = true

[params]

  # Metadata for search engines and social sharing
  author = "Tiago Sommer Damasceno"
  description = "Tiago's personal website"
  shareImage = "images/social.jpg"
  twitterHandle = "tiagosomda"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/background.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Notes : where I blog"
        url = "https://notes.tiago.dev"

      [[params.links.list1.link]]
        text = "LinkedIn : professional stuff"
        url = "https://www.linkedin.com/in/tiagosomda/"

      [[params.links.list1.link]]
        text = "Want to chat about career planning?"
        url = "https://calendly.com/tiagosomda/career-mentorship"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Made by me"

      [[params.links.list2.link]]
        text = "Camp Fireworks : VR game"
        url = "https://sidequestvr.com/app/1287/camp-fireworks"

      [[params.links.list2.link]]      
        text = "Striking Thoughts : creative outlet"
        url = "http://www.strikingthoughts.io/"

      [[params.links.list2.link]]      
        text = "Gists : some useful scripts"
        url = "https://gist.github.com/tiagosomda" 

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
